# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jatin Rohilla
email: jatin.mca17.du@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio site of Jatin Rohilla
    
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jatin69.github.io" # the base hostname & protocol for your site

#sidebar
default-image: default-project-banner.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.
# i am not using sidebar

#footer
copyright:
  name:  Jatin Rohilla
  link: 'http://github.com/jatin69'

# Build settings
markdown: kramdown
permalink: /:title/

# pagination usecases are very specifics, does not work natively on custom collections, eg projects
# paginate: 9
# paginate_path: /page-:num/

# Tracker
# this is my id, use yours if you fork it
analytics: UA-142349334-2

# Comments
# go to disqus site and create a admin dashboard for your site
disqus: yes
disqus-shortname: jatin69-github-io

# social links
facebook: http://facebook.com/jatinrohilla69
twitter: http://twitter.com/jatinrohilla69
github: http://github.com/jatin69
linkedin: https://www.linkedin.com/in/jatinrohilla/
email: jatin.mca17.du@gmail.com

# Sass style
sass:
  style: compressed

collections:
  projects  :
    output    : true
    permalink : /:collection/:name
    # permalink : /:collection/:path

# Ruby Gems
# octopress debugger is a great tool for debugging, google it to know more
plugins: [jekyll-seo-tag, octopress-debugger]

# this tell jekyll to build markdown files from `_pages` folder
include: ['_pages']

# feeds are only relevant for posts, not useful for my projects
allowPostFeeds: false